#!/usr/bin/env node
/** Wait for this stamp's CI, then merge only the reviewed candidate. */
import { spawnSync } from "node:child_process";
import { pathToFileURL } from "node:url";

const execute = (command, args) => spawnSync(command, args, { encoding: "utf8", timeout: 25 * 60_000, maxBuffer: 4 * 1024 * 1024 });
const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

export async function mergeStamp(number, branch, { run = execute, sleep = delay } = {}) {
  if (!/^\d+$/.test(String(number)) || !branch?.startsWith("release/stamp-")) throw new Error("Expected a stamp PR number and branch.");
  const command = (bin, args) => {
    const result = run(bin, args);
    if (result.status !== 0) throw new Error(`${bin} ${args.join(" ")} failed: ${result.stderr || result.error?.message || result.status}`);
    return result.stdout.trim();
  };
  const json = (args) => JSON.parse(command("gh", args));
  const head = command("git", ["rev-parse", "HEAD"]);
  const prArgs = ["pr", "view", String(number), "--json", "state,headRefOid,autoMergeRequest"];
  const assertCandidate = () => {
    const pr = json(prArgs);
    if (pr.state !== "OPEN" || pr.headRefOid !== head || pr.autoMergeRequest) throw new Error("Stamp candidate changed or auto-merge is still armed.");
  };
  assertCandidate();
  const listArgs = ["run", "list", "--workflow", "ci.yml", "--branch", branch, "--event", "workflow_dispatch", "--limit", "30", "--json", "databaseId,headSha"];
  const previous = new Set(json(listArgs).map((item) => item.databaseId));
  command("gh", ["workflow", "run", "ci.yml", "--ref", branch, "-f", "verification=presubmit"]);
  let ci;
  for (let attempt = 0; attempt < 12; attempt += 1) {
    ci = json(listArgs).find((item) => item.headSha === head && !previous.has(item.databaseId));
    if (ci) break;
    await sleep(10_000);
  }
  if (!ci) throw new Error("The dispatched stamp CI run did not become visible; refusing to merge.");
  command("gh", ["run", "watch", String(ci.databaseId), "--exit-status", "--interval", "10"]);
  const verdict = json(["run", "view", String(ci.databaseId), "--json", "status,conclusion,headSha,jobs"]);
  if (
    verdict.headSha !== head ||
    verdict.status !== "completed" ||
    verdict.conclusion !== "success" ||
    !verdict.jobs.some((job) => job.name === "CI complete" && job.conclusion === "success")
  ) {
    throw new Error("The exact stamp candidate has not passed CI; refusing to merge.");
  }
  assertCandidate();
  command("git", ["fetch", "--no-tags", "origin", "main:refs/remotes/origin/main"]);
  const contains = run("git", ["merge-base", "--is-ancestor", "origin/main", head]);
  if (contains.status === 1) {
    command("gh", ["workflow", "run", "stamp.yml", "--ref", "main"]);
    return { merged: false, refreshQueued: true, reason: "main advanced while stamp CI ran" };
  }
  if (contains.status !== 0) throw new Error("Could not verify the stamp's base; refusing to merge.");
  command("gh", ["pr", "merge", String(number), "--squash", "--match-head-commit", head]);
  const merged = json(["pr", "view", String(number), "--json", "state,headRefOid,mergeCommit"]);
  if (merged.state !== "MERGED" || merged.headRefOid !== head || !merged.mergeCommit?.oid) throw new Error("Stamp merge was not confirmed.");

  // A base can still advance between fetch and merge. Recheck generated bytes on
  // merged main and explicitly queue recovery; token-originated merges do not
  // necessarily trigger another push workflow. Deployment keeps its own guard.
  command("git", ["fetch", "--no-tags", "origin", "main:refs/remotes/origin/main"]);
  command("git", ["merge-base", "--is-ancestor", merged.mergeCommit.oid, "origin/main"]);
  command("git", ["checkout", "-B", "main", "origin/main"]);
  const checked = run("npm", ["run", "check:stamped-tree"]);
  if (checked.status !== 0) {
    command("gh", ["workflow", "run", "stamp.yml", "--ref", "main"]);
    throw new Error("Merged main failed the stamp guard; recovery queued. Do not deploy this tree.");
  }
  return { merged: true, head, mergeCommit: merged.mergeCommit.oid, ci: ci.databaseId };
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  try {
    console.log(JSON.stringify(await mergeStamp(process.argv[2], process.argv[3])));
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
